name: fatint
description: Big fat integer support for Dart
version: 1.0.0
homepage: https://github.com/desktop-dart/fatint
author: Ravi Teja Gudapati <tejainece@gmail.com>

documentation:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  rational: ^0.1.11

dev_dependencies:
  test: ^0.12.0
